@startuml
'https://plantuml.com/class-diagram

solution43 <-- websiteGenerator

class solution43 {
String siteName
String author
String inJS
String inCSS
websiteGenerator()
}

class websiteGenerator{
String siteName
String author
createWebsite()
createJSFolder()
createCSSFolder()
createHTML()
}


@enduml